// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state8 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_2566;
reg   [0:0] or_cond_i_i_reg_2575;
reg   [0:0] icmp_reg_2519;
reg   [0:0] tmp_1_reg_2510;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_2615;
reg   [0:0] or_cond_i_reg_2615_pp0_iter2_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] t_V_2_reg_606;
wire   [1:0] tmp_6_fu_617_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond390_i_fu_633_p2;
wire    ap_CS_fsm_state3;
wire   [9:0] i_V_fu_639_p2;
reg   [9:0] i_V_reg_2505;
wire   [0:0] tmp_1_fu_645_p2;
wire   [0:0] tmp_72_0_0_not_fu_651_p2;
reg   [0:0] tmp_72_0_0_not_reg_2514;
wire   [0:0] icmp_fu_667_p2;
wire   [0:0] tmp_9_fu_673_p2;
reg   [0:0] tmp_9_reg_2524;
wire   [0:0] tmp_116_0_1_fu_679_p2;
reg   [0:0] tmp_116_0_1_reg_2528;
wire   [0:0] tmp_2_fu_685_p2;
reg   [0:0] tmp_2_reg_2532;
wire   [1:0] row_assign_9_0_0_t_fu_839_p2;
reg   [1:0] row_assign_9_0_0_t_reg_2545;
wire   [1:0] row_assign_9_0_1_t_fu_877_p2;
reg   [1:0] row_assign_9_0_1_t_reg_2552;
wire   [1:0] row_assign_9_0_2_t_fu_915_p2;
reg   [1:0] row_assign_9_0_2_t_reg_2559;
wire   [0:0] exitcond389_i_fu_925_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op211_read_state5;
reg    ap_predicate_op223_read_state5;
reg    ap_predicate_op253_read_state5;
reg    ap_predicate_op265_read_state5;
reg    ap_predicate_op292_read_state5;
reg    ap_predicate_op301_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_reg_2566_pp0_iter1_reg;
wire   [10:0] j_V_fu_931_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_979_p2;
wire   [1:0] tmp_50_fu_1039_p1;
reg   [1:0] tmp_50_reg_2579;
wire   [0:0] brmerge_fu_1043_p2;
reg   [0:0] brmerge_reg_2584;
reg   [10:0] k_buf_0_val_3_addr_reg_2597;
reg   [10:0] k_buf_0_val_4_addr_reg_2603;
reg   [10:0] k_buf_0_val_5_addr_reg_2609;
wire   [0:0] or_cond_i_fu_1061_p2;
reg   [0:0] or_cond_i_reg_2615_pp0_iter1_reg;
reg   [10:0] k_buf_1_val_3_addr_reg_2619;
reg   [10:0] k_buf_1_val_4_addr_reg_2625;
reg   [10:0] k_buf_1_val_5_addr_reg_2631;
reg   [10:0] k_buf_2_val_3_addr_reg_2637;
reg   [10:0] k_buf_2_val_4_addr_reg_2643;
reg   [10:0] k_buf_2_val_5_addr_reg_2649;
wire   [7:0] src_kernel_win_0_va_6_fu_1205_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_2655;
wire   [7:0] src_kernel_win_0_va_7_fu_1223_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2662;
wire   [7:0] src_kernel_win_0_va_8_fu_1241_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_2669;
wire   [7:0] src_kernel_win_1_va_6_fu_1373_p3;
reg   [7:0] src_kernel_win_1_va_6_reg_2675;
wire   [7:0] src_kernel_win_1_va_7_fu_1391_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2682;
wire   [7:0] src_kernel_win_1_va_8_fu_1409_p3;
reg   [7:0] src_kernel_win_1_va_8_reg_2689;
wire   [7:0] src_kernel_win_2_va_9_fu_1523_p3;
reg   [7:0] src_kernel_win_2_va_9_reg_2695;
wire   [7:0] src_kernel_win_2_va_10_fu_1541_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2702;
wire   [7:0] src_kernel_win_2_va_11_fu_1559_p3;
reg   [7:0] src_kernel_win_2_va_11_reg_2709;
reg   [0:0] isneg_reg_2715;
wire   [7:0] p_Val2_1_fu_1712_p2;
reg   [7:0] p_Val2_1_reg_2721;
wire   [0:0] not_i_i_i_fu_1728_p2;
reg   [0:0] not_i_i_i_reg_2726;
reg   [0:0] isneg_1_reg_2731;
wire   [7:0] p_Val2_3_fu_1880_p2;
reg   [7:0] p_Val2_3_reg_2737;
wire   [0:0] not_i_i_i1_fu_1896_p2;
reg   [0:0] not_i_i_i1_reg_2742;
reg   [0:0] isneg_2_reg_2747;
wire   [7:0] p_Val2_6_fu_2048_p2;
reg   [7:0] p_Val2_6_reg_2753;
wire   [0:0] not_i_i_i2_fu_2064_p2;
reg   [0:0] not_i_i_i2_reg_2758;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_584;
wire   [0:0] tmp_7_fu_623_p2;
reg   [9:0] t_V_reg_595;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_25_fu_1048_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_242;
reg   [7:0] src_kernel_win_0_va_1_fu_246;
reg   [7:0] src_kernel_win_0_va_2_fu_250;
reg   [7:0] src_kernel_win_0_va_3_fu_254;
reg   [7:0] src_kernel_win_0_va_4_fu_258;
reg   [7:0] src_kernel_win_0_va_5_fu_262;
reg   [7:0] src_kernel_win_1_va_fu_266;
reg   [7:0] src_kernel_win_1_va_1_fu_270;
reg   [7:0] src_kernel_win_1_va_2_fu_274;
reg   [7:0] src_kernel_win_1_va_3_fu_278;
reg   [7:0] src_kernel_win_1_va_4_fu_282;
reg   [7:0] src_kernel_win_1_va_5_fu_286;
reg   [7:0] src_kernel_win_2_va_fu_290;
reg   [7:0] src_kernel_win_2_va_1_fu_294;
reg   [7:0] src_kernel_win_2_va_2_fu_298;
reg   [7:0] src_kernel_win_2_va_3_fu_302;
reg   [7:0] src_kernel_win_2_va_4_fu_306;
reg   [7:0] src_kernel_win_2_va_5_fu_310;
reg   [7:0] right_border_buf_0_s_fu_314;
wire   [7:0] col_buf_0_val_0_0_fu_1110_p3;
reg   [7:0] right_border_buf_0_1_fu_318;
reg   [7:0] right_border_buf_2_s_fu_322;
reg   [7:0] right_border_buf_0_2_fu_326;
wire   [7:0] col_buf_0_val_1_0_fu_1129_p3;
reg   [7:0] right_border_buf_0_3_fu_330;
reg   [7:0] right_border_buf_2_1_fu_334;
wire   [7:0] col_buf_2_val_2_0_fu_1475_p3;
reg   [7:0] right_border_buf_0_4_fu_338;
wire   [7:0] col_buf_0_val_2_0_fu_1148_p3;
reg   [7:0] right_border_buf_0_5_fu_342;
reg   [7:0] right_border_buf_2_2_fu_346;
reg   [7:0] right_border_buf_1_s_fu_350;
wire   [7:0] col_buf_1_val_0_0_fu_1278_p3;
reg   [7:0] right_border_buf_1_1_fu_354;
reg   [7:0] right_border_buf_2_3_fu_358;
wire   [7:0] col_buf_2_val_1_0_fu_1456_p3;
reg   [7:0] right_border_buf_1_2_fu_362;
wire   [7:0] col_buf_1_val_1_0_fu_1297_p3;
reg   [7:0] right_border_buf_1_3_fu_366;
reg   [7:0] right_border_buf_2_4_fu_370;
reg   [7:0] right_border_buf_1_4_fu_374;
wire   [7:0] col_buf_1_val_2_0_fu_1316_p3;
reg   [7:0] right_border_buf_1_5_fu_378;
reg   [7:0] right_border_buf_2_5_fu_382;
wire   [7:0] col_buf_2_val_0_0_fu_1437_p3;
wire   [8:0] tmp_fu_657_p4;
wire   [10:0] t_V_cast_fu_629_p1;
wire   [1:0] tmp_8_fu_691_p1;
wire   [10:0] tmp_3_fu_695_p2;
wire   [0:0] tmp_10_fu_707_p3;
wire   [0:0] tmp_4_fu_721_p2;
wire   [0:0] rev_fu_715_p2;
wire   [0:0] tmp_11_fu_733_p3;
wire   [10:0] p_assign_7_fu_741_p2;
wire   [10:0] p_p2_i426_i_fu_747_p3;
wire   [1:0] tmp_12_fu_755_p1;
wire   [10:0] p_assign_6_0_1_fu_771_p2;
wire   [10:0] p_assign_6_0_2_fu_797_p2;
wire   [0:0] tmp_13_fu_759_p2;
wire   [1:0] p_assign_8_fu_765_p2;
wire   [0:0] or_cond_i425_i_fu_727_p2;
wire   [1:0] tmp_140_cast_fu_701_p2;
wire   [1:0] p_p2_i426_i_0_p_assig_fu_823_p3;
wire   [1:0] y_1_fu_831_p3;
wire   [1:0] tmp_17_fu_793_p1;
wire   [0:0] tmp_15_fu_785_p3;
wire   [1:0] tmp_24_fu_851_p2;
wire   [1:0] tmp_30_fu_857_p1;
wire   [0:0] tmp_14_fu_777_p3;
wire   [1:0] tmp_31_fu_861_p3;
wire   [1:0] tmp_16_fu_845_p2;
wire   [1:0] tmp_32_fu_869_p3;
wire   [1:0] tmp_22_fu_819_p1;
wire   [0:0] tmp_20_fu_811_p3;
wire   [1:0] tmp_35_fu_889_p2;
wire   [1:0] tmp_38_fu_895_p1;
wire   [0:0] tmp_19_fu_803_p3;
wire   [1:0] tmp_39_fu_899_p3;
wire   [1:0] tmp_34_fu_883_p2;
wire   [1:0] tmp_36_fu_907_p3;
wire   [9:0] tmp_40_fu_937_p4;
wire   [11:0] t_V_2_cast_fu_921_p1;
wire   [11:0] ImagLoc_x_fu_953_p2;
wire   [0:0] tmp_41_fu_959_p3;
wire   [0:0] tmp_21_fu_973_p2;
wire   [0:0] rev1_fu_967_p2;
wire   [0:0] tmp_43_fu_985_p3;
wire   [11:0] p_assign_1_fu_993_p2;
wire   [11:0] p_p2_i_i_fu_999_p3;
wire   [0:0] tmp_23_fu_1007_p2;
wire   [11:0] p_assign_2_fu_1013_p2;
wire   [11:0] p_p2_i_i_p_assign_2_fu_1019_p3;
wire  signed [11:0] x_fu_1027_p3;
wire  signed [31:0] x_cast_fu_1035_p1;
wire   [0:0] icmp1_fu_947_p2;
wire   [1:0] col_assign_2_0_t_fu_1093_p2;
wire   [7:0] tmp_26_fu_1098_p5;
wire   [7:0] tmp_27_fu_1117_p5;
wire   [7:0] tmp_28_fu_1136_p5;
wire   [7:0] tmp_29_fu_1194_p5;
wire   [7:0] tmp_33_fu_1212_p5;
wire   [7:0] tmp_37_fu_1230_p5;
wire   [7:0] tmp_44_fu_1266_p5;
wire   [7:0] tmp_45_fu_1285_p5;
wire   [7:0] tmp_46_fu_1304_p5;
wire   [7:0] tmp_47_fu_1362_p5;
wire   [7:0] tmp_48_fu_1380_p5;
wire   [7:0] tmp_49_fu_1398_p5;
wire   [7:0] tmp_56_fu_1425_p5;
wire   [7:0] tmp_57_fu_1444_p5;
wire   [7:0] tmp_58_fu_1463_p5;
wire   [7:0] tmp_59_fu_1512_p5;
wire   [7:0] tmp_60_fu_1530_p5;
wire   [7:0] tmp_61_fu_1548_p5;
wire   [8:0] tmp_160_0_0_2_cast_fu_1579_p1;
wire   [8:0] OP1_V_0_0_cast_fu_1575_p1;
wire  signed [8:0] p_Val2_10_0_0_2_fu_1582_p2;
wire   [8:0] p_shl_fu_1592_p3;
wire   [9:0] p_shl_cast_fu_1600_p1;
wire  signed [9:0] r_V_7_0_1_fu_1604_p2;
wire   [8:0] r_V_7_0_1_2_fu_1622_p3;
wire   [8:0] OP1_V_0_2_cast_fu_1638_p1;
wire  signed [8:0] r_V_7_0_2_fu_1642_p2;
wire  signed [10:0] tmp_160_0_2_cast_fu_1648_p1;
wire  signed [10:0] tmp_160_0_1_cast_fu_1610_p1;
wire   [9:0] tmp_160_0_2_2_cast_c_fu_1656_p1;
wire  signed [9:0] p_Val2_10_0_0_2_ca_fu_1588_p1;
wire   [9:0] tmp4_fu_1665_p2;
wire   [10:0] tmp_160_0_1_cast_64_fu_1629_p1;
wire  signed [10:0] tmp4_cast_fu_1671_p1;
wire   [10:0] tmp2_fu_1659_p2;
wire   [10:0] tmp3_fu_1675_p2;
wire   [10:0] p_Val2_2_fu_1681_p2;
wire   [7:0] tmp_55_fu_1618_p1;
wire   [7:0] tmp_53_fu_1614_p1;
wire   [7:0] tmp_63_fu_1652_p1;
wire   [7:0] tmp_62_fu_1633_p2;
wire   [7:0] tmp7_fu_1701_p2;
wire   [7:0] tmp5_fu_1695_p2;
wire   [7:0] tmp6_fu_1706_p2;
wire   [2:0] tmp_42_fu_1718_p4;
wire   [8:0] tmp_160_1_0_2_cast_fu_1747_p1;
wire   [8:0] OP1_V_1_0_cast_fu_1743_p1;
wire  signed [8:0] p_Val2_10_1_0_2_fu_1750_p2;
wire   [8:0] p_shl1_fu_1760_p3;
wire   [9:0] p_shl1_cast_fu_1768_p1;
wire  signed [9:0] r_V_7_1_1_fu_1772_p2;
wire   [8:0] r_V_7_1_1_2_fu_1790_p3;
wire   [8:0] OP1_V_1_2_cast_fu_1806_p1;
wire  signed [8:0] r_V_7_1_2_fu_1810_p2;
wire  signed [10:0] tmp_160_1_2_cast_fu_1816_p1;
wire  signed [10:0] tmp_160_1_1_cast_fu_1778_p1;
wire   [9:0] tmp_160_1_2_2_cast_c_fu_1824_p1;
wire  signed [9:0] p_Val2_10_1_0_2_ca_fu_1756_p1;
wire   [9:0] tmp12_fu_1833_p2;
wire   [10:0] tmp_160_1_1_cast_66_fu_1797_p1;
wire  signed [10:0] tmp12_cast_fu_1839_p1;
wire   [10:0] tmp10_fu_1827_p2;
wire   [10:0] tmp11_fu_1843_p2;
wire   [10:0] p_Val2_5_fu_1849_p2;
wire   [7:0] tmp_70_fu_1786_p1;
wire   [7:0] tmp_69_fu_1782_p1;
wire   [7:0] tmp_72_fu_1820_p1;
wire   [7:0] tmp_71_fu_1801_p2;
wire   [7:0] tmp15_fu_1869_p2;
wire   [7:0] tmp13_fu_1863_p2;
wire   [7:0] tmp14_fu_1874_p2;
wire   [2:0] tmp_54_fu_1886_p4;
wire   [8:0] tmp_160_2_0_2_cast_fu_1915_p1;
wire   [8:0] OP1_V_2_0_cast_fu_1911_p1;
wire  signed [8:0] p_Val2_10_2_0_2_fu_1918_p2;
wire   [8:0] p_shl2_fu_1928_p3;
wire   [9:0] p_shl2_cast_fu_1936_p1;
wire  signed [9:0] r_V_7_2_1_fu_1940_p2;
wire   [8:0] r_V_7_2_1_2_fu_1958_p3;
wire   [8:0] OP1_V_2_2_cast_fu_1974_p1;
wire  signed [8:0] r_V_7_2_2_fu_1978_p2;
wire  signed [10:0] tmp_160_2_2_cast_fu_1984_p1;
wire  signed [10:0] tmp_160_2_1_cast_fu_1946_p1;
wire   [9:0] tmp_160_2_2_2_cast_c_fu_1992_p1;
wire  signed [9:0] p_Val2_10_2_0_2_ca_fu_1924_p1;
wire   [9:0] tmp20_fu_2001_p2;
wire   [10:0] tmp_160_2_1_cast_68_fu_1965_p1;
wire  signed [10:0] tmp20_cast_fu_2007_p1;
wire   [10:0] tmp18_fu_1995_p2;
wire   [10:0] tmp19_fu_2011_p2;
wire   [10:0] p_Val2_s_fu_2017_p2;
wire   [7:0] tmp_78_fu_1954_p1;
wire   [7:0] tmp_77_fu_1950_p1;
wire   [7:0] tmp_80_fu_1988_p1;
wire   [7:0] tmp_79_fu_1969_p2;
wire   [7:0] tmp23_fu_2037_p2;
wire   [7:0] tmp21_fu_2031_p2;
wire   [7:0] tmp22_fu_2042_p2;
wire   [2:0] tmp_64_fu_2054_p4;
wire   [0:0] tmp_i_i_fu_2178_p2;
wire   [0:0] overflow_fu_2183_p2;
wire   [0:0] tmp_i_i_65_fu_2196_p2;
wire   [7:0] p_mux_i_i_cast_fu_2188_p3;
wire   [0:0] tmp_i_i1_fu_2209_p2;
wire   [0:0] overflow_1_fu_2214_p2;
wire   [0:0] tmp_i_i1_67_fu_2227_p2;
wire   [7:0] p_mux_i_i30_cast_fu_2219_p3;
wire   [0:0] tmp_i_i2_fu_2240_p2;
wire   [0:0] overflow_2_fu_2245_p2;
wire   [0:0] tmp_i_i2_69_fu_2258_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2250_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_559;
reg    ap_condition_62;
reg    ap_condition_553;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2597),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2603),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2609),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2619),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2625),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2631),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2637),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2643),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2649),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U31(
    .din0(right_border_buf_0_s_fu_314),
    .din1(right_border_buf_0_1_fu_318),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_26_fu_1098_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U32(
    .din0(right_border_buf_0_2_fu_326),
    .din1(right_border_buf_0_3_fu_330),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_27_fu_1117_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U33(
    .din0(right_border_buf_0_4_fu_338),
    .din1(right_border_buf_0_5_fu_342),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_28_fu_1136_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U34(
    .din0(col_buf_0_val_0_0_fu_1110_p3),
    .din1(col_buf_0_val_1_0_fu_1129_p3),
    .din2(col_buf_0_val_2_0_fu_1148_p3),
    .din3(row_assign_9_0_0_t_reg_2545),
    .dout(tmp_29_fu_1194_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U35(
    .din0(col_buf_0_val_0_0_fu_1110_p3),
    .din1(col_buf_0_val_1_0_fu_1129_p3),
    .din2(col_buf_0_val_2_0_fu_1148_p3),
    .din3(row_assign_9_0_1_t_reg_2552),
    .dout(tmp_33_fu_1212_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U36(
    .din0(col_buf_0_val_0_0_fu_1110_p3),
    .din1(col_buf_0_val_1_0_fu_1129_p3),
    .din2(col_buf_0_val_2_0_fu_1148_p3),
    .din3(row_assign_9_0_2_t_reg_2559),
    .dout(tmp_37_fu_1230_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U37(
    .din0(right_border_buf_1_s_fu_350),
    .din1(right_border_buf_1_1_fu_354),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_44_fu_1266_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U38(
    .din0(right_border_buf_1_2_fu_362),
    .din1(right_border_buf_1_3_fu_366),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_45_fu_1285_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U39(
    .din0(right_border_buf_1_4_fu_374),
    .din1(right_border_buf_1_5_fu_378),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_46_fu_1304_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U40(
    .din0(col_buf_1_val_0_0_fu_1278_p3),
    .din1(col_buf_1_val_1_0_fu_1297_p3),
    .din2(col_buf_1_val_2_0_fu_1316_p3),
    .din3(row_assign_9_0_0_t_reg_2545),
    .dout(tmp_47_fu_1362_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U41(
    .din0(col_buf_1_val_0_0_fu_1278_p3),
    .din1(col_buf_1_val_1_0_fu_1297_p3),
    .din2(col_buf_1_val_2_0_fu_1316_p3),
    .din3(row_assign_9_0_1_t_reg_2552),
    .dout(tmp_48_fu_1380_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U42(
    .din0(col_buf_1_val_0_0_fu_1278_p3),
    .din1(col_buf_1_val_1_0_fu_1297_p3),
    .din2(col_buf_1_val_2_0_fu_1316_p3),
    .din3(row_assign_9_0_2_t_reg_2559),
    .dout(tmp_49_fu_1398_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U43(
    .din0(right_border_buf_2_5_fu_382),
    .din1(right_border_buf_2_4_fu_370),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_56_fu_1425_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U44(
    .din0(right_border_buf_2_3_fu_358),
    .din1(right_border_buf_2_2_fu_346),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_57_fu_1444_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U45(
    .din0(right_border_buf_2_1_fu_334),
    .din1(right_border_buf_2_s_fu_322),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1093_p2),
    .dout(tmp_58_fu_1463_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U46(
    .din0(col_buf_2_val_0_0_fu_1437_p3),
    .din1(col_buf_2_val_1_0_fu_1456_p3),
    .din2(col_buf_2_val_2_0_fu_1475_p3),
    .din3(row_assign_9_0_0_t_reg_2545),
    .dout(tmp_59_fu_1512_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U47(
    .din0(col_buf_2_val_0_0_fu_1437_p3),
    .din1(col_buf_2_val_1_0_fu_1456_p3),
    .din2(col_buf_2_val_2_0_fu_1475_p3),
    .din3(row_assign_9_0_1_t_reg_2552),
    .dout(tmp_60_fu_1530_p5)
);

sobel_edge_detectncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_edge_detectncg_U48(
    .din0(col_buf_2_val_0_0_fu_1437_p3),
    .din1(col_buf_2_val_1_0_fu_1456_p3),
    .din2(col_buf_2_val_2_0_fu_1475_p3),
    .din3(row_assign_9_0_2_t_reg_2559),
    .dout(tmp_61_fu_1548_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_925_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond390_i_fu_633_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state5)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond390_i_fu_633_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_925_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_606 <= j_V_fu_931_p2;
    end else if (((exitcond390_i_fu_633_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_2_reg_606 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_595 <= 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_595 <= i_V_reg_2505;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_5_reg_584 <= 2'd0;
    end else if (((tmp_7_fu_623_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_584 <= tmp_6_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_925_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2584 <= brmerge_fu_1043_p2;
        k_buf_0_val_3_addr_reg_2597 <= tmp_25_fu_1048_p1;
        k_buf_0_val_4_addr_reg_2603 <= tmp_25_fu_1048_p1;
        k_buf_0_val_5_addr_reg_2609 <= tmp_25_fu_1048_p1;
        k_buf_1_val_3_addr_reg_2619 <= tmp_25_fu_1048_p1;
        k_buf_1_val_4_addr_reg_2625 <= tmp_25_fu_1048_p1;
        k_buf_1_val_5_addr_reg_2631 <= tmp_25_fu_1048_p1;
        k_buf_2_val_3_addr_reg_2637 <= tmp_25_fu_1048_p1;
        k_buf_2_val_4_addr_reg_2643 <= tmp_25_fu_1048_p1;
        k_buf_2_val_5_addr_reg_2649 <= tmp_25_fu_1048_p1;
        or_cond_i_i_reg_2575 <= or_cond_i_i_fu_979_p2;
        or_cond_i_reg_2615 <= or_cond_i_fu_1061_p2;
        tmp_50_reg_2579 <= tmp_50_fu_1039_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond389_i_reg_2566 <= exitcond389_i_fu_925_p2;
        exitcond389_i_reg_2566_pp0_iter1_reg <= exitcond389_i_reg_2566;
        or_cond_i_reg_2615_pp0_iter1_reg <= or_cond_i_reg_2615;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2505 <= i_V_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_633_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2519 <= icmp_fu_667_p2;
        row_assign_9_0_0_t_reg_2545 <= row_assign_9_0_0_t_fu_839_p2;
        row_assign_9_0_1_t_reg_2552 <= row_assign_9_0_1_t_fu_877_p2;
        row_assign_9_0_2_t_reg_2559 <= row_assign_9_0_2_t_fu_915_p2;
        tmp_116_0_1_reg_2528 <= tmp_116_0_1_fu_679_p2;
        tmp_1_reg_2510 <= tmp_1_fu_645_p2;
        tmp_2_reg_2532 <= tmp_2_fu_685_p2;
        tmp_72_0_0_not_reg_2514 <= tmp_72_0_0_not_fu_651_p2;
        tmp_9_reg_2524 <= tmp_9_fu_673_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2615_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        isneg_1_reg_2731 <= p_Val2_5_fu_1849_p2[32'd10];
        isneg_2_reg_2747 <= p_Val2_s_fu_2017_p2[32'd10];
        isneg_reg_2715 <= p_Val2_2_fu_1681_p2[32'd10];
        not_i_i_i1_reg_2742 <= not_i_i_i1_fu_1896_p2;
        not_i_i_i2_reg_2758 <= not_i_i_i2_fu_2064_p2;
        not_i_i_i_reg_2726 <= not_i_i_i_fu_1728_p2;
        p_Val2_1_reg_2721 <= p_Val2_1_fu_1712_p2;
        p_Val2_3_reg_2737 <= p_Val2_3_fu_1880_p2;
        p_Val2_6_reg_2753 <= p_Val2_6_fu_2048_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_2615_pp0_iter2_reg <= or_cond_i_reg_2615_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1))) begin
        right_border_buf_0_1_fu_318 <= right_border_buf_0_s_fu_314;
        right_border_buf_0_2_fu_326 <= col_buf_0_val_1_0_fu_1129_p3;
        right_border_buf_0_3_fu_330 <= right_border_buf_0_2_fu_326;
        right_border_buf_0_4_fu_338 <= col_buf_0_val_2_0_fu_1148_p3;
        right_border_buf_0_5_fu_342 <= right_border_buf_0_4_fu_338;
        right_border_buf_0_s_fu_314 <= col_buf_0_val_0_0_fu_1110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1))) begin
        right_border_buf_1_1_fu_354 <= right_border_buf_1_s_fu_350;
        right_border_buf_1_2_fu_362 <= col_buf_1_val_1_0_fu_1297_p3;
        right_border_buf_1_3_fu_366 <= right_border_buf_1_2_fu_362;
        right_border_buf_1_4_fu_374 <= col_buf_1_val_2_0_fu_1316_p3;
        right_border_buf_1_5_fu_378 <= right_border_buf_1_4_fu_374;
        right_border_buf_1_s_fu_350 <= col_buf_1_val_0_0_fu_1278_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1))) begin
        right_border_buf_2_1_fu_334 <= col_buf_2_val_2_0_fu_1475_p3;
        right_border_buf_2_2_fu_346 <= right_border_buf_2_3_fu_358;
        right_border_buf_2_3_fu_358 <= col_buf_2_val_1_0_fu_1456_p3;
        right_border_buf_2_4_fu_370 <= right_border_buf_2_5_fu_382;
        right_border_buf_2_5_fu_382 <= col_buf_2_val_0_0_fu_1437_p3;
        right_border_buf_2_s_fu_322 <= right_border_buf_2_1_fu_334;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2566_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_246 <= src_kernel_win_0_va_fu_242;
        src_kernel_win_0_va_2_fu_250 <= src_kernel_win_0_va_7_reg_2662;
        src_kernel_win_0_va_3_fu_254 <= src_kernel_win_0_va_2_fu_250;
        src_kernel_win_0_va_4_fu_258 <= src_kernel_win_0_va_8_reg_2669;
        src_kernel_win_0_va_5_fu_262 <= src_kernel_win_0_va_4_fu_258;
        src_kernel_win_0_va_fu_242 <= src_kernel_win_0_va_6_reg_2655;
        src_kernel_win_1_va_1_fu_270 <= src_kernel_win_1_va_fu_266;
        src_kernel_win_1_va_2_fu_274 <= src_kernel_win_1_va_7_reg_2682;
        src_kernel_win_1_va_3_fu_278 <= src_kernel_win_1_va_2_fu_274;
        src_kernel_win_1_va_4_fu_282 <= src_kernel_win_1_va_8_reg_2689;
        src_kernel_win_1_va_5_fu_286 <= src_kernel_win_1_va_4_fu_282;
        src_kernel_win_1_va_fu_266 <= src_kernel_win_1_va_6_reg_2675;
        src_kernel_win_2_va_1_fu_294 <= src_kernel_win_2_va_fu_290;
        src_kernel_win_2_va_2_fu_298 <= src_kernel_win_2_va_10_reg_2702;
        src_kernel_win_2_va_3_fu_302 <= src_kernel_win_2_va_2_fu_298;
        src_kernel_win_2_va_4_fu_306 <= src_kernel_win_2_va_11_reg_2709;
        src_kernel_win_2_va_5_fu_310 <= src_kernel_win_2_va_4_fu_306;
        src_kernel_win_2_va_fu_290 <= src_kernel_win_2_va_9_reg_2695;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2566 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_6_reg_2655 <= src_kernel_win_0_va_6_fu_1205_p3;
        src_kernel_win_0_va_7_reg_2662 <= src_kernel_win_0_va_7_fu_1223_p3;
        src_kernel_win_0_va_8_reg_2669 <= src_kernel_win_0_va_8_fu_1241_p3;
        src_kernel_win_1_va_6_reg_2675 <= src_kernel_win_1_va_6_fu_1373_p3;
        src_kernel_win_1_va_7_reg_2682 <= src_kernel_win_1_va_7_fu_1391_p3;
        src_kernel_win_1_va_8_reg_2689 <= src_kernel_win_1_va_8_fu_1409_p3;
        src_kernel_win_2_va_10_reg_2702 <= src_kernel_win_2_va_10_fu_1541_p3;
        src_kernel_win_2_va_11_reg_2709 <= src_kernel_win_2_va_11_fu_1559_p3;
        src_kernel_win_2_va_9_reg_2695 <= src_kernel_win_2_va_9_fu_1523_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond390_i_fu_633_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_633_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op223_read_state5 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_559)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op223_read_state5 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op265_read_state5 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_559)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op265_read_state5 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op301_read_state5 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_559)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op301_read_state5 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op223_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op211_read_state5 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op253_read_state5 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op301_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op292_read_state5 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_623_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_633_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_953_p2 = ($signed(12'd4095) + $signed(t_V_2_cast_fu_921_p1));

assign OP1_V_0_0_cast_fu_1575_p1 = src_kernel_win_0_va_5_fu_262;

assign OP1_V_0_2_cast_fu_1638_p1 = src_kernel_win_0_va_1_fu_246;

assign OP1_V_1_0_cast_fu_1743_p1 = src_kernel_win_1_va_5_fu_286;

assign OP1_V_1_2_cast_fu_1806_p1 = src_kernel_win_1_va_1_fu_270;

assign OP1_V_2_0_cast_fu_1911_p1 = src_kernel_win_2_va_5_fu_310;

assign OP1_V_2_2_cast_fu_1974_p1 = src_kernel_win_2_va_1_fu_294;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op301_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op292_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op265_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op253_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op223_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op211_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op301_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op292_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op265_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op253_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op223_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op211_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op301_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op292_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op265_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op253_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op223_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op211_read_state5 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op301_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op292_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op265_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op253_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op223_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op211_read_state5 == 1'b1)));
end

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter3 = (((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2615_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_553 = ((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_condition_559 = ((tmp_116_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_condition_62 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op211_read_state5 = ((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_predicate_op253_read_state5 = ((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_predicate_op265_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_predicate_op292_read_state5 = ((or_cond_i_i_reg_2575 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond389_i_reg_2566 == 1'd0));
end

always @ (*) begin
    ap_predicate_op301_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2575 == 1'd1) & (exitcond389_i_reg_2566 == 1'd0));
end

assign brmerge_fu_1043_p2 = (tmp_72_0_0_not_reg_2514 | tmp_21_fu_973_p2);

assign col_assign_2_0_t_fu_1093_p2 = (tmp_50_reg_2579 ^ 2'd3);

assign col_buf_0_val_0_0_fu_1110_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_26_fu_1098_p5);

assign col_buf_0_val_1_0_fu_1129_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_27_fu_1117_p5);

assign col_buf_0_val_2_0_fu_1148_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_28_fu_1136_p5);

assign col_buf_1_val_0_0_fu_1278_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_44_fu_1266_p5);

assign col_buf_1_val_1_0_fu_1297_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_45_fu_1285_p5);

assign col_buf_1_val_2_0_fu_1316_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_46_fu_1304_p5);

assign col_buf_2_val_0_0_fu_1437_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_56_fu_1425_p5);

assign col_buf_2_val_1_0_fu_1456_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_57_fu_1444_p5);

assign col_buf_2_val_2_0_fu_1475_p3 = ((brmerge_reg_2584[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_58_fu_1463_p5);

assign exitcond389_i_fu_925_p2 = ((t_V_2_reg_606 == 11'd1282) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_633_p2 = ((t_V_reg_595 == 10'd722) ? 1'b1 : 1'b0);

assign i_V_fu_639_p2 = (t_V_reg_595 + 10'd1);

assign icmp1_fu_947_p2 = ((tmp_40_fu_937_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_667_p2 = ((tmp_fu_657_p4 != 9'd0) ? 1'b1 : 1'b0);

assign j_V_fu_931_p2 = (t_V_2_reg_606 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_25_fu_1048_p1;

assign k_buf_0_val_4_address0 = tmp_25_fu_1048_p1;

assign k_buf_0_val_5_address0 = tmp_25_fu_1048_p1;

assign k_buf_1_val_3_address0 = tmp_25_fu_1048_p1;

assign k_buf_1_val_4_address0 = tmp_25_fu_1048_p1;

assign k_buf_1_val_5_address0 = tmp_25_fu_1048_p1;

assign k_buf_2_val_3_address0 = tmp_25_fu_1048_p1;

assign k_buf_2_val_4_address0 = tmp_25_fu_1048_p1;

assign k_buf_2_val_5_address0 = tmp_25_fu_1048_p1;

assign not_i_i_i1_fu_1896_p2 = ((tmp_54_fu_1886_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i2_fu_2064_p2 = ((tmp_64_fu_2054_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_1728_p2 = ((tmp_42_fu_1718_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i425_i_fu_727_p2 = (tmp_4_fu_721_p2 & rev_fu_715_p2);

assign or_cond_i_fu_1061_p2 = (icmp_reg_2519 & icmp1_fu_947_p2);

assign or_cond_i_i_fu_979_p2 = (tmp_21_fu_973_p2 & rev1_fu_967_p2);

assign overflow_1_fu_2214_p2 = (tmp_i_i1_fu_2209_p2 & not_i_i_i1_reg_2742);

assign overflow_2_fu_2245_p2 = (tmp_i_i2_fu_2240_p2 & not_i_i_i2_reg_2758);

assign overflow_fu_2183_p2 = (tmp_i_i_fu_2178_p2 & not_i_i_i_reg_2726);

assign p_Val2_10_0_0_2_ca_fu_1588_p1 = p_Val2_10_0_0_2_fu_1582_p2;

assign p_Val2_10_0_0_2_fu_1582_p2 = (tmp_160_0_0_2_cast_fu_1579_p1 - OP1_V_0_0_cast_fu_1575_p1);

assign p_Val2_10_1_0_2_ca_fu_1756_p1 = p_Val2_10_1_0_2_fu_1750_p2;

assign p_Val2_10_1_0_2_fu_1750_p2 = (tmp_160_1_0_2_cast_fu_1747_p1 - OP1_V_1_0_cast_fu_1743_p1);

assign p_Val2_10_2_0_2_ca_fu_1924_p1 = p_Val2_10_2_0_2_fu_1918_p2;

assign p_Val2_10_2_0_2_fu_1918_p2 = (tmp_160_2_0_2_cast_fu_1915_p1 - OP1_V_2_0_cast_fu_1911_p1);

assign p_Val2_1_fu_1712_p2 = (tmp5_fu_1695_p2 + tmp6_fu_1706_p2);

assign p_Val2_2_fu_1681_p2 = (tmp2_fu_1659_p2 + tmp3_fu_1675_p2);

assign p_Val2_3_fu_1880_p2 = (tmp13_fu_1863_p2 + tmp14_fu_1874_p2);

assign p_Val2_5_fu_1849_p2 = (tmp10_fu_1827_p2 + tmp11_fu_1843_p2);

assign p_Val2_6_fu_2048_p2 = (tmp21_fu_2031_p2 + tmp22_fu_2042_p2);

assign p_Val2_s_fu_2017_p2 = (tmp18_fu_1995_p2 + tmp19_fu_2011_p2);

assign p_assign_1_fu_993_p2 = (12'd1 - t_V_2_cast_fu_921_p1);

assign p_assign_2_fu_1013_p2 = ($signed(12'd2558) - $signed(p_p2_i_i_fu_999_p3));

assign p_assign_6_0_1_fu_771_p2 = ($signed(11'd2046) + $signed(t_V_cast_fu_629_p1));

assign p_assign_6_0_2_fu_797_p2 = ($signed(11'd2045) + $signed(t_V_cast_fu_629_p1));

assign p_assign_7_fu_741_p2 = (11'd1 - t_V_cast_fu_629_p1);

assign p_assign_8_fu_765_p2 = ($signed(2'd2) - $signed(tmp_12_fu_755_p1));

assign p_dst_data_stream_0_V_din = ((tmp_i_i_65_fu_2196_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2188_p3 : p_Val2_1_reg_2721);

assign p_dst_data_stream_1_V_din = ((tmp_i_i1_67_fu_2227_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_2219_p3 : p_Val2_3_reg_2737);

assign p_dst_data_stream_2_V_din = ((tmp_i_i2_69_fu_2258_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2250_p3 : p_Val2_6_reg_2753);

assign p_mux_i_i30_cast_fu_2219_p3 = ((tmp_i_i1_fu_2209_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2250_p3 = ((tmp_i_i2_fu_2240_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_2188_p3 = ((tmp_i_i_fu_2178_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i426_i_0_p_assig_fu_823_p3 = ((tmp_13_fu_759_p2[0:0] === 1'b1) ? tmp_12_fu_755_p1 : p_assign_8_fu_765_p2);

assign p_p2_i426_i_fu_747_p3 = ((tmp_11_fu_733_p3[0:0] === 1'b1) ? p_assign_7_fu_741_p2 : tmp_3_fu_695_p2);

assign p_p2_i_i_fu_999_p3 = ((tmp_43_fu_985_p3[0:0] === 1'b1) ? p_assign_1_fu_993_p2 : ImagLoc_x_fu_953_p2);

assign p_p2_i_i_p_assign_2_fu_1019_p3 = ((tmp_23_fu_1007_p2[0:0] === 1'b1) ? p_p2_i_i_fu_999_p3 : p_assign_2_fu_1013_p2);

assign p_shl1_cast_fu_1768_p1 = p_shl1_fu_1760_p3;

assign p_shl1_fu_1760_p3 = {{src_kernel_win_1_va_3_fu_278}, {1'd0}};

assign p_shl2_cast_fu_1936_p1 = p_shl2_fu_1928_p3;

assign p_shl2_fu_1928_p3 = {{src_kernel_win_2_va_3_fu_302}, {1'd0}};

assign p_shl_cast_fu_1600_p1 = p_shl_fu_1592_p3;

assign p_shl_fu_1592_p3 = {{src_kernel_win_0_va_3_fu_254}, {1'd0}};

assign r_V_7_0_1_2_fu_1622_p3 = {{src_kernel_win_0_va_7_reg_2662}, {1'd0}};

assign r_V_7_0_1_fu_1604_p2 = (10'd0 - p_shl_cast_fu_1600_p1);

assign r_V_7_0_2_fu_1642_p2 = (9'd0 - OP1_V_0_2_cast_fu_1638_p1);

assign r_V_7_1_1_2_fu_1790_p3 = {{src_kernel_win_1_va_7_reg_2682}, {1'd0}};

assign r_V_7_1_1_fu_1772_p2 = (10'd0 - p_shl1_cast_fu_1768_p1);

assign r_V_7_1_2_fu_1810_p2 = (9'd0 - OP1_V_1_2_cast_fu_1806_p1);

assign r_V_7_2_1_2_fu_1958_p3 = {{src_kernel_win_2_va_10_reg_2702}, {1'd0}};

assign r_V_7_2_1_fu_1940_p2 = (10'd0 - p_shl2_cast_fu_1936_p1);

assign r_V_7_2_2_fu_1978_p2 = (9'd0 - OP1_V_2_2_cast_fu_1974_p1);

assign rev1_fu_967_p2 = (tmp_41_fu_959_p3 ^ 1'd1);

assign rev_fu_715_p2 = (tmp_10_fu_707_p3 ^ 1'd1);

assign row_assign_9_0_0_t_fu_839_p2 = (y_1_fu_831_p3 ^ 2'd3);

assign row_assign_9_0_1_t_fu_877_p2 = (tmp_32_fu_869_p3 ^ 2'd3);

assign row_assign_9_0_2_t_fu_915_p2 = (tmp_36_fu_907_p3 ^ 2'd3);

assign src_kernel_win_0_va_6_fu_1205_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_29_fu_1194_p5 : col_buf_0_val_0_0_fu_1110_p3);

assign src_kernel_win_0_va_7_fu_1223_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_33_fu_1212_p5 : col_buf_0_val_1_0_fu_1129_p3);

assign src_kernel_win_0_va_8_fu_1241_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_37_fu_1230_p5 : col_buf_0_val_2_0_fu_1148_p3);

assign src_kernel_win_1_va_6_fu_1373_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_47_fu_1362_p5 : col_buf_1_val_0_0_fu_1278_p3);

assign src_kernel_win_1_va_7_fu_1391_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_48_fu_1380_p5 : col_buf_1_val_1_0_fu_1297_p3);

assign src_kernel_win_1_va_8_fu_1409_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_49_fu_1398_p5 : col_buf_1_val_2_0_fu_1316_p3);

assign src_kernel_win_2_va_10_fu_1541_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_60_fu_1530_p5 : col_buf_2_val_1_0_fu_1456_p3);

assign src_kernel_win_2_va_11_fu_1559_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_61_fu_1548_p5 : col_buf_2_val_2_0_fu_1475_p3);

assign src_kernel_win_2_va_9_fu_1523_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_59_fu_1512_p5 : col_buf_2_val_0_0_fu_1437_p3);

assign t_V_2_cast_fu_921_p1 = t_V_2_reg_606;

assign t_V_cast_fu_629_p1 = t_V_reg_595;

assign tmp10_fu_1827_p2 = ($signed(tmp_160_1_2_cast_fu_1816_p1) + $signed(tmp_160_1_1_cast_fu_1778_p1));

assign tmp11_fu_1843_p2 = ($signed(tmp_160_1_1_cast_66_fu_1797_p1) + $signed(tmp12_cast_fu_1839_p1));

assign tmp12_cast_fu_1839_p1 = $signed(tmp12_fu_1833_p2);

assign tmp12_fu_1833_p2 = ($signed(tmp_160_1_2_2_cast_c_fu_1824_p1) + $signed(p_Val2_10_1_0_2_ca_fu_1756_p1));

assign tmp13_fu_1863_p2 = (tmp_70_fu_1786_p1 + tmp_69_fu_1782_p1);

assign tmp14_fu_1874_p2 = (tmp_71_fu_1801_p2 + tmp15_fu_1869_p2);

assign tmp15_fu_1869_p2 = (src_kernel_win_1_va_6_reg_2675 + tmp_72_fu_1820_p1);

assign tmp18_fu_1995_p2 = ($signed(tmp_160_2_2_cast_fu_1984_p1) + $signed(tmp_160_2_1_cast_fu_1946_p1));

assign tmp19_fu_2011_p2 = ($signed(tmp_160_2_1_cast_68_fu_1965_p1) + $signed(tmp20_cast_fu_2007_p1));

assign tmp20_cast_fu_2007_p1 = $signed(tmp20_fu_2001_p2);

assign tmp20_fu_2001_p2 = ($signed(tmp_160_2_2_2_cast_c_fu_1992_p1) + $signed(p_Val2_10_2_0_2_ca_fu_1924_p1));

assign tmp21_fu_2031_p2 = (tmp_78_fu_1954_p1 + tmp_77_fu_1950_p1);

assign tmp22_fu_2042_p2 = (tmp_79_fu_1969_p2 + tmp23_fu_2037_p2);

assign tmp23_fu_2037_p2 = (src_kernel_win_2_va_9_reg_2695 + tmp_80_fu_1988_p1);

assign tmp2_fu_1659_p2 = ($signed(tmp_160_0_2_cast_fu_1648_p1) + $signed(tmp_160_0_1_cast_fu_1610_p1));

assign tmp3_fu_1675_p2 = ($signed(tmp_160_0_1_cast_64_fu_1629_p1) + $signed(tmp4_cast_fu_1671_p1));

assign tmp4_cast_fu_1671_p1 = $signed(tmp4_fu_1665_p2);

assign tmp4_fu_1665_p2 = ($signed(tmp_160_0_2_2_cast_c_fu_1656_p1) + $signed(p_Val2_10_0_0_2_ca_fu_1588_p1));

assign tmp5_fu_1695_p2 = (tmp_55_fu_1618_p1 + tmp_53_fu_1614_p1);

assign tmp6_fu_1706_p2 = (tmp_62_fu_1633_p2 + tmp7_fu_1701_p2);

assign tmp7_fu_1701_p2 = (src_kernel_win_0_va_6_reg_2655 + tmp_63_fu_1652_p1);

assign tmp_10_fu_707_p3 = tmp_3_fu_695_p2[32'd10];

assign tmp_116_0_1_fu_679_p2 = ((t_V_reg_595 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_733_p3 = tmp_3_fu_695_p2[32'd10];

assign tmp_12_fu_755_p1 = p_p2_i426_i_fu_747_p3[1:0];

assign tmp_13_fu_759_p2 = (($signed(p_p2_i426_i_fu_747_p3) < $signed(11'd720)) ? 1'b1 : 1'b0);

assign tmp_140_cast_fu_701_p2 = ($signed(2'd3) + $signed(tmp_8_fu_691_p1));

assign tmp_14_fu_777_p3 = p_assign_6_0_1_fu_771_p2[32'd10];

assign tmp_15_fu_785_p3 = p_assign_6_0_1_fu_771_p2[32'd10];

assign tmp_160_0_0_2_cast_fu_1579_p1 = src_kernel_win_0_va_8_reg_2669;

assign tmp_160_0_1_cast_64_fu_1629_p1 = r_V_7_0_1_2_fu_1622_p3;

assign tmp_160_0_1_cast_fu_1610_p1 = r_V_7_0_1_fu_1604_p2;

assign tmp_160_0_2_2_cast_c_fu_1656_p1 = src_kernel_win_0_va_6_reg_2655;

assign tmp_160_0_2_cast_fu_1648_p1 = r_V_7_0_2_fu_1642_p2;

assign tmp_160_1_0_2_cast_fu_1747_p1 = src_kernel_win_1_va_8_reg_2689;

assign tmp_160_1_1_cast_66_fu_1797_p1 = r_V_7_1_1_2_fu_1790_p3;

assign tmp_160_1_1_cast_fu_1778_p1 = r_V_7_1_1_fu_1772_p2;

assign tmp_160_1_2_2_cast_c_fu_1824_p1 = src_kernel_win_1_va_6_reg_2675;

assign tmp_160_1_2_cast_fu_1816_p1 = r_V_7_1_2_fu_1810_p2;

assign tmp_160_2_0_2_cast_fu_1915_p1 = src_kernel_win_2_va_11_reg_2709;

assign tmp_160_2_1_cast_68_fu_1965_p1 = r_V_7_2_1_2_fu_1958_p3;

assign tmp_160_2_1_cast_fu_1946_p1 = r_V_7_2_1_fu_1940_p2;

assign tmp_160_2_2_2_cast_c_fu_1992_p1 = src_kernel_win_2_va_9_reg_2695;

assign tmp_160_2_2_cast_fu_1984_p1 = r_V_7_2_2_fu_1978_p2;

assign tmp_16_fu_845_p2 = (tmp_8_fu_691_p1 ^ 2'd2);

assign tmp_17_fu_793_p1 = t_V_reg_595[1:0];

assign tmp_19_fu_803_p3 = p_assign_6_0_2_fu_797_p2[32'd10];

assign tmp_1_fu_645_p2 = ((t_V_reg_595 < 10'd720) ? 1'b1 : 1'b0);

assign tmp_20_fu_811_p3 = p_assign_6_0_2_fu_797_p2[32'd10];

assign tmp_21_fu_973_p2 = (($signed(ImagLoc_x_fu_953_p2) < $signed(12'd1280)) ? 1'b1 : 1'b0);

assign tmp_22_fu_819_p1 = t_V_reg_595[1:0];

assign tmp_23_fu_1007_p2 = (($signed(p_p2_i_i_fu_999_p3) < $signed(12'd1280)) ? 1'b1 : 1'b0);

assign tmp_24_fu_851_p2 = ($signed(2'd2) - $signed(tmp_17_fu_793_p1));

assign tmp_25_fu_1048_p1 = $unsigned(x_cast_fu_1035_p1);

assign tmp_2_fu_685_p2 = ((t_V_reg_595 > 10'd720) ? 1'b1 : 1'b0);

assign tmp_30_fu_857_p1 = p_assign_6_0_1_fu_771_p2[1:0];

assign tmp_31_fu_861_p3 = ((tmp_15_fu_785_p3[0:0] === 1'b1) ? tmp_24_fu_851_p2 : tmp_30_fu_857_p1);

assign tmp_32_fu_869_p3 = ((tmp_14_fu_777_p3[0:0] === 1'b1) ? tmp_31_fu_861_p3 : tmp_16_fu_845_p2);

assign tmp_34_fu_883_p2 = (2'd1 + tmp_8_fu_691_p1);

assign tmp_35_fu_889_p2 = (tmp_22_fu_819_p1 ^ 2'd3);

assign tmp_36_fu_907_p3 = ((tmp_19_fu_803_p3[0:0] === 1'b1) ? tmp_39_fu_899_p3 : tmp_34_fu_883_p2);

assign tmp_38_fu_895_p1 = p_assign_6_0_2_fu_797_p2[1:0];

assign tmp_39_fu_899_p3 = ((tmp_20_fu_811_p3[0:0] === 1'b1) ? tmp_35_fu_889_p2 : tmp_38_fu_895_p1);

assign tmp_3_fu_695_p2 = ($signed(11'd2047) + $signed(t_V_cast_fu_629_p1));

assign tmp_40_fu_937_p4 = {{t_V_2_reg_606[10:1]}};

assign tmp_41_fu_959_p3 = ImagLoc_x_fu_953_p2[32'd11];

assign tmp_42_fu_1718_p4 = {{p_Val2_2_fu_1681_p2[10:8]}};

assign tmp_43_fu_985_p3 = ImagLoc_x_fu_953_p2[32'd11];

assign tmp_4_fu_721_p2 = (($signed(tmp_3_fu_695_p2) < $signed(11'd720)) ? 1'b1 : 1'b0);

assign tmp_50_fu_1039_p1 = x_fu_1027_p3[1:0];

assign tmp_53_fu_1614_p1 = p_Val2_10_0_0_2_fu_1582_p2[7:0];

assign tmp_54_fu_1886_p4 = {{p_Val2_5_fu_1849_p2[10:8]}};

assign tmp_55_fu_1618_p1 = r_V_7_0_1_fu_1604_p2[7:0];

assign tmp_62_fu_1633_p2 = src_kernel_win_0_va_7_reg_2662 << 8'd1;

assign tmp_63_fu_1652_p1 = r_V_7_0_2_fu_1642_p2[7:0];

assign tmp_64_fu_2054_p4 = {{p_Val2_s_fu_2017_p2[10:8]}};

assign tmp_69_fu_1782_p1 = p_Val2_10_1_0_2_fu_1750_p2[7:0];

assign tmp_6_fu_617_p2 = (tmp_5_reg_584 + 2'd1);

assign tmp_70_fu_1786_p1 = r_V_7_1_1_fu_1772_p2[7:0];

assign tmp_71_fu_1801_p2 = src_kernel_win_1_va_7_reg_2682 << 8'd1;

assign tmp_72_0_0_not_fu_651_p2 = (tmp_1_fu_645_p2 ^ 1'd1);

assign tmp_72_fu_1820_p1 = r_V_7_1_2_fu_1810_p2[7:0];

assign tmp_77_fu_1950_p1 = p_Val2_10_2_0_2_fu_1918_p2[7:0];

assign tmp_78_fu_1954_p1 = r_V_7_2_1_fu_1940_p2[7:0];

assign tmp_79_fu_1969_p2 = src_kernel_win_2_va_10_reg_2702 << 8'd1;

assign tmp_7_fu_623_p2 = ((tmp_5_reg_584 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_80_fu_1988_p1 = r_V_7_2_2_fu_1978_p2[7:0];

assign tmp_8_fu_691_p1 = t_V_reg_595[1:0];

assign tmp_9_fu_673_p2 = ((t_V_reg_595 == 10'd1) ? 1'b1 : 1'b0);

assign tmp_fu_657_p4 = {{t_V_reg_595[9:1]}};

assign tmp_i_i1_67_fu_2227_p2 = (overflow_1_fu_2214_p2 | isneg_1_reg_2731);

assign tmp_i_i1_fu_2209_p2 = (isneg_1_reg_2731 ^ 1'd1);

assign tmp_i_i2_69_fu_2258_p2 = (overflow_2_fu_2245_p2 | isneg_2_reg_2747);

assign tmp_i_i2_fu_2240_p2 = (isneg_2_reg_2747 ^ 1'd1);

assign tmp_i_i_65_fu_2196_p2 = (overflow_fu_2183_p2 | isneg_reg_2715);

assign tmp_i_i_fu_2178_p2 = (isneg_reg_2715 ^ 1'd1);

assign x_cast_fu_1035_p1 = x_fu_1027_p3;

assign x_fu_1027_p3 = ((or_cond_i_i_fu_979_p2[0:0] === 1'b1) ? ImagLoc_x_fu_953_p2 : p_p2_i_i_p_assign_2_fu_1019_p3);

assign y_1_fu_831_p3 = ((or_cond_i425_i_fu_727_p2[0:0] === 1'b1) ? tmp_140_cast_fu_701_p2 : p_p2_i426_i_0_p_assig_fu_823_p3);

endmodule //Filter2D
