# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint_zybo.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sobel_edge_detect_0_1/design_1_sobel_edge_detect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sobel_edge_detect_0_1 || ORIG_REF_NAME==design_1_sobel_edge_detect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dvi2rgb_0_9/design_1_dvi2rgb_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dvi2rgb_0_9 || ORIG_REF_NAME==design_1_dvi2rgb_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_vid_in_axi4s_0_1 || ORIG_REF_NAME==design_1_v_vid_in_axi4s_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_1/design_1_v_axi4s_vid_out_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_1/design_1_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_1 || ORIG_REF_NAME==design_1_v_tc_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2vga_0_1/design_1_rgb2vga_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2vga_0_1 || ORIG_REF_NAME==design_1_rgb2vga_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_2/design_1_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_2 || ORIG_REF_NAME==design_1_xlconstant_0_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
