:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2018.2
:: Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

E:/Xilinx/Vivado/Vivado/2018.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg484-1 ../xilinx_com_hls_sobel_edge_detect_1_0.zip
